"$schema" = 'https://starship.rs/config-schema.json'

format = """[](surface)\
$os\
$username\
[](bg:emerald fg:surface)\
$directory\
[](fg:emerald bg:dark-emerald)\
$git_branch\
$git_status\
[](fg:dark-emerald bg:gold)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:gold bg:dark-gold)\
$docker_context\
[](fg:dark-gold bg:crimson)\
$time\
[ ](fg:crimson)\
$line_break$character"""

palette = 'elwyn_arch'
[palettes.elwyn_arch]
text = "#FFFFFF"
surface = "#313244"
mantle = "#181825"
crimson = "#9e2732"
dark-crimson = "#671921"
dark-silver = "#878787"
silver = "#f8f8f8"
emerald = "#16c299"
dark-emerald = "#0c5040"
gold = "#d7c68f"
dark-gold = "#b79c53"

[os]
disabled = false
style = "bg:surface fg:text"

[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:surface fg:text"
style_root = "bg:surface fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:emerald"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"
"Desktop" = ""
"Duckstation" = "󰇥"
"Videos" = ""
"~" = "󰛓"

[git_branch]
symbol = ""
style = "bg:dark-emerald"
format = '[[ $symbol $branch ](fg:silver bg:dark-emerald)]($style)'

[git_status]
style = "bg:crimson"
format = '[[($all_status$ahead_behind )](fg:silver bg:dark-emerald)]($style)'

[nodejs]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:dark-gold bg:gold)]($style)'

[c]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:dark-gold bg:gold)]($style)'


[python]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:dark-gold bg:gold)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:silver bg:crimson)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ➜](bold emerald)'
error_symbol = '[ x](bold crimson)'
vimcmd_symbol = '[](bold emerald)'
vimcmd_replace_one_symbol = '[](bold fg:gold)'
vimcmd_replace_symbol = '[](bold fg:gold)'
vimcmd_visual_symbol = '[](bold fg:gold)'
